New back
projetoKhali/api4back pull request #18
Opened 2024-04-09 00:30 UTC by markusgomes

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- Alteração e configuração de banco, postgres.  

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- Criação de classes: repository, service, iservice e controller.

2024-04-09 03:39 UTC, paulo-granthon requested changes

2024-04-09 03:39 UTC, paulo-granthon commented on create_database.sql
> +)*/
código comentado

2024-04-09 03:39 UTC, paulo-granthon commented on pom.xml
> +		</dependency>
essa dependência não será usada

2024-04-09 03:39 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/ApiApplication.java
> +public class ApiApplication {
é necessário reverter a alteração no nome da classe, também é necessário reverter `src/test/java/com/fatec/springapi4/ApiApplicationTests.java`

Ambos os arquivos também precisam ser renomeados refletindo o nome da classe

2024-04-09 03:39 UTC, paulo-granthon commented on .github/pull_request_template.md
esse arquivo precisa ser restaurado

2024-04-09 03:39 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/controller/ExpertiseController.java
> +    private IExpertiseService expServ;
não precisa abreviar o nome das variáveis, fazer isso faz com que seja mais difícil de entender o código 
```suggestion
    private IExpertiseService expertiseService;
```

2024-04-09 03:39 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/entity/Partner.java
> +.entity;
faltou remover essa quebra de linha
```suggestion
package com.fatec.springapi4.entity;
```

esse overlook também está presente nos arquivos `/entity/Qualifier.java` e `/entity/Track.java`

2024-04-09 03:39 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/entity/Qualifier.java
> +    private String name;
```suggestion
    private String name;
```

2024-04-10 12:17 UTC, Incivius submitted a review, later dismissed

2024-04-10 12:26 UTC, taniacruzz approved these changes, later dismissed

2024-04-10 20:41 UTC, paulo-granthon approved these changes

2024-04-10 20:59 UTC, taniacruzz approved these changes

2024-04-10 21:01 UTC, merged