Filter partner
projetoKhali/api4back pull request #28
Opened 2024-04-20 18:55 UTC by ryanlanziloti

# Objetivo:
`Qual o propósito / escopo dessas alterações?`
resolve #27

- 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- 

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-04-21 21:07 UTC, paulo-granthon requested changes

2024-04-21 21:07 UTC, paulo-granthon commented on src/main/resources/application.properties
Alterações ao `application.properties` não devem ser commitadas ao remoto considerando que as credenciais que você usa podem ser diferentes das que os outros membros usam.

Faz mais sentido deixar os valores anteriores pois representam as credenciais usadas para conectar com o banco de dados em container definido no arquivo `docker-compose`

2024-04-21 21:07 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/repository/PartnerRepository.java
> +    public List<Partner> filterPartner(@Param("country") List<String> country);*/
Pode remover esse comentário

2024-04-21 21:07 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/repository/PartnerRepository.java
> +import java.util.List;
Esses imports foram adicionados mas não estão sendo usados já que o código que usava eles está comentado.

Podemos remover eles também, nesse caso esse arquivo fica sem nenhuma alteração

2024-04-21 21:07 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/controller/PartnerController.java
> +                                       @RequestParam(value = "companyId", required = false)String companyId,
Acho que o `companyId` não é um bom candidato pra esse filtro pois o mesmo representa uma identificação própria da Oracle que refletimos no nosso banco. 

Apesar desse campo não estar com `UNIQUE` no DDL, na prática acredito que os valores dele não vão se repetir em múltiplos partners, logo não faz sentido incluirmos nessa função. 

Em contrapartida, temos outros campos `boolean` assim como o `status` que podem ser incluídos aqui

2024-04-21 21:07 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/service/PartnerService.java
> +    public List<Partner> filterPartner(String country, String companyId, boolean status){
Acho que `status` tem que ser `Boolean` (classe) em vez de `boolean` (primitivo) pra permitir um valor de `null`.

Se não, acredito que caso não seja passado um `status` na requisição, a query irá considerar como `false` e só retornará os `Partner` com `status` = `false`.

Devemos permitir `true`, `false` e `null`.

2024-04-21 21:27 UTC, ryanlanziloti reviewed
resolve #27

2024-04-22 04:33 UTC, paulo-granthon submitted a review, later dismissed
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette4.wikia.nocookie.net%2Fpyruslords%2Fimages%2F0%2F06%2FNot_Bad_Reggie.gif%2Frevision%2Flatest%3Fcb%3D20150517050220&f=1&nofb=1&ipt=c8427095d8be6393e445ca208a8e4809b57013b405477d606f351552824d5fa8&ipo=images)

2024-04-28 01:19 UTC, paulo-granthon requested changes

2024-04-28 01:19 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/controller/UserController.java
> +}
podemos trocar o nome da função já que agora ela aceita múltiplos parâmetros além do nome

2024-04-29 22:53 UTC, paulo-granthon approved these changes

2024-04-29 23:07 UTC, NicSouza approved these changes

2024-04-30 00:18 UTC, merged