add track_metrics view
projetoKhali/api4back pull request #39
Opened 2024-05-04 21:15 UTC by JhonatanLop

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- resolve #31
- unificar dados em uma view para facilitar o trabalho no backend em uma requisição só

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- criação de uma view e um endpoint que retorna as informações da view

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- DTO da view
- End-point da view

2024-05-04 23:04 UTC, JhonatanLop commented
além da view. foi adicionado o back-end de mapeamento da view

consulta por id da track
![image](https://github.com/projetoKhali/api4back/assets/111443621/67d12c52-0fb9-4131-ab88-6a62c2b99dcb)

consulta em todas
![image](https://github.com/projetoKhali/api4back/assets/111443621/a20c9127-d5a6-4796-a00f-6654c4c56d85)

2024-05-04 23:20 UTC, paulo-granthon requested changes

2024-05-04 23:20 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/entity/TrackMetrics.java
> +    private Integer QualifierCompletionPercentage;
acho que faz sentido colocar um `average` nos nomes dessas variáveis, se não fica implícito que é soma (pelo menos eu tenho essa impressão).

fora isso tá show, parabéns

2024-05-04 23:43 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/TrackMetrics.java
> +    private Integer QualifierCompletionPercentage;
usei a forma abreviada "avg..." 👍

2024-05-05 03:14 UTC, paulo-granthon approved these changes
![](https://c.tenor.com/-2X9RJQkqhgAAAAd/tenor.gif)

2024-05-05 03:29 UTC, Incivius approved these changes

2024-05-05 14:20 UTC, merged