partner metrics
projetoKhali/api4back pull request #52
Opened 2024-05-14 00:17 UTC by ryanlanziloti

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`
- resolve #30 
- resolve #51 
- 

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-05-16 04:57 UTC, paulo-granthon requested changes

2024-05-16 04:57 UTC, paulo-granthon commented on src/main/resources/application.properties
opa, alterações ao `application.properties` não devem ser commitadas.

se vc usa parâmetros diferentes aos que estão no repositório para conectar com o banco, as alterações devem ser ignoradas ao efetuar commits;

caso vc use `git add .`, vc pode continuar usando porém remover o `application.properties` da area de `staged` ao usar `git restore --staged src/main/resources/application.properties`;

através da aba `source control` no vscode vc tbm consegue tirar o arquivo do `staged` após o `git add .` antes do commit;

outra forma de vc garantir que o `application.properties` não seja incluído no commit é utilizando regex para especificar os arquivos que vc quer no add. por exemplo, se vc tem os arquivos:

- a.java
- b.java
- a.md

vc consegue usar:

- `git add *.java` para adicionar os 2 primeiro arquivos;
- `git add b*` para adicionar o arquivo 2;
- `git add a*` para adicionar o arquivo 1 e 3;

dessa forma vc consegue, por exemplo, incluir todos os arquivos da pasta `src/main/java` ao usar `git add src/main/java/*`, sem adicionar o `application.properties` que fica no `src/main/resources`

<hr>

é importante corrigir isso pq se não acho que vc consegue imaginar a quantidade de commit desnecessário de cada pessoa alterando o `application.properties` para adequar ao setup dele(a)

2024-05-18 14:38 UTC, Incivius approved these changes

2024-05-18 17:45 UTC, taniacruzz approved these changes

2024-05-18 19:43 UTC, paulo-granthon approved these changes

2024-05-21 00:03 UTC, Incivius approved these changes

2024-05-21 00:14 UTC, merged