novas seeds
projetoKhali/api4back pull request #61
Opened 2024-05-24 01:27 UTC by ryanlanziloti

# Objetivo:
`Qual o propósito / escopo dessas alterações?`
#60 
- 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- 

# Pendências:
`Pendências notáveis referentes ao escopo dessas alterações que continuam em aberto.`

- 

# Prosseguimento:
`Possíveis caminhos a seguir para solucionar as pendências mencionadas.`

-

2024-05-26 02:25 UTC, paulo-granthon requested changes
podemos trabalhar melhor nesses nomes para que façam sentido para o cliente durante a apresentação

2024-05-26 02:25 UTC, paulo-granthon commented on db/postgres_seeds.sql
> +('Specialist');
esses não são nomes que fazem sentido pra qualifier

2024-05-26 02:25 UTC, paulo-granthon commented on db/postgres_seeds.sql
> +('Post-launch Support', '2024-09-15', NULL);
esses nomes fazem mais sentido pra "títulos de sprint de um projeto" do q tracks nas quais são agrupadas qualificações em variados tópicos

2024-05-27 01:15 UTC, paulo-granthon approved these changes

2024-05-27 01:17 UTC, Incivius approved these changes

2024-05-27 01:54 UTC, merged