view PartnerReports
projetoKhali/api4back pull request #73
Opened 2024-06-11 01:22 UTC by ryanlanziloti

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- #66

2024-06-11 13:33 UTC, paulo-granthon requested changes

2024-06-11 13:33 UTC, paulo-granthon commented on src/main/resources/application.properties
não é pra subir `application.properties`

2024-06-11 13:33 UTC, paulo-granthon commented on src/main/java/com/fatec/springapi4/repository/PartnerReportsRepository.java
> +    @SuppressWarnings("null")
isso me parece um code smell, o problema aqui é que pode retornar `null`?

2024-06-12 14:15 UTC, ryanlanziloti commented on src/main/java/com/fatec/springapi4/repository/PartnerReportsRepository.java
> +    @SuppressWarnings("null")
Segredo

2024-06-13 23:43 UTC, paulo-granthon approved these changes

2024-06-14 10:58 UTC, merged