Entities
projetoKhali/api4back pull request #9
Opened 2024-04-04 14:10 UTC by taniacruzz

# Objetivo:
`Qual o propósito / escopo dessas alterações?`

- resolve #8 

# Solução:
`Quais estratégias foram adotadas durante as alterações em questão?`

- criação de todas as classes e das notações de coluna, constraints, chaves primárias, estrangeiras e etc. Não foram usadas chaves compostas, ao inves disso foi usada uniqueConstraint e criação de um id para as classes que representam as relações entre entidades.

2024-04-04 14:26 UTC, paulo-granthon submitted a review, later dismissed

2024-04-04 14:26 UTC, paulo-granthon commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @Column(name = ex_name)
`ex_id` e `ex_name` nessas anotações `@Column` não precisam das aspas?

```suggestion
    @Column(name = "ex_id")
    private Long id;

    @Column(name = "ex_name")
```

2024-04-04 20:42 UTC, JhonatanLop requested changes
Solicito mudança apenas no código da classe `Parner` pra usar "city" ao invés de "state" já que é o único dado que temos. O resto é apenas sugestão.

2024-04-04 20:42 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    private List<Qualifier> qualifiers;
Não seria interessante usar um `Set` ao invés de `List` pros qualificadores? Onde um parceiro não vai ter o mesmo qualificador duas vezes e sim um qualificador vai servir para mais de uma expertize?

> Lembrando que o Set é uma lista onde os itens dentro não se repetem

2024-04-04 20:42 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Partner.java
> +    @Column(name = pt_state)
Como no dado enviado pelo parceiro académico não tem a coluna `state`, vamos usar `city` mesmo que já vem no modelo de dados fornecido.

2024-04-04 20:42 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/PartnerQualifier.java
> +@Table(uniqueConstraints = { @UniqueConstraint(columnNames = { "pt_id", "ql_id" }) })
acho q faltou colocar o nome da tabela na anotação `@Table` ou isso só é necessário quando o nome da classe é diferente do nome da tabela?

2024-04-04 20:42 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    private List<Qualifier> qualifiers;
como a tabela Expertise_Qualifier é uma tabela de relação many-to-meny seria bom usar a anotação ` @ManyToMany(fetch = FetchType.EAGER)`

`FetchType.EAGER` diz ao JPA para já buscar os dados relacionados sempre que a entidade principal for carregada. Por exemplo, no contexto atual, quando uma expertize for buscada, todos os seus qulificadores também serão carregados.

tem um exemplo no código backend da aula de Lab4
```java
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "Expertize_Qualifier",
        joinColumns = { @JoinColumn(name = "ex_id")},
        inverseJoinColumns = { @JoinColumn(name = "ql_id") }
        )
    private Set<Qualifier> qualifiers;
```
código de exemplo [aqui](https://github.com/JhonatanLop/Lab4/blob/main/src/main/java/com/khali/lab4/entity/Usuario.java)

`@JoinTable`  define qual tabela será a relação passando o nome como parâmetro
`joinColumns` indica a coluna usada na tabela de relação pela entidade principal "Expertise"
`inverseJoinColumns` indica a coluna usada na tabela de relação pela outra entidade

2024-04-05 01:28 UTC, taniacruzz commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @Column(name = ex_name)
corrigido

2024-04-05 01:28 UTC, taniacruzz commented on src/main/java/com/fatec/springAPI4/entity/PartnerQualifier.java
> +@Table(uniqueConstraints = { @UniqueConstraint(columnNames = { "pt_id", "ql_id" }) })
alterações feitas. apenas não foi feita classe especifica para a tabela Expertise_Qualifier, já que essa relação não tem dado novo.

2024-04-05 22:21 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @ManyToOne
fui tentar executar o projeto e o java reclamou que a anotação @ManyToOne não foi importada.

2024-04-06 18:09 UTC, paulo-granthon commented
Incluí algumas alterações que removem a capitalização das pastas.

O github possui um ***bug*** que faz com que as pastas permaneçam com o mesmo nome ao efetuar alterações que mexem apenas na capitalização dos nomes das pastas sem trocar o conteúdo em sí, por exemplo:

Ao trocar `springAPI4` para `springApi4` no commit https://github.com/projetoKhali/api4back/pull/9/commits/540b546f0efe8225c71f10054339f2cc679067c6, é possível observar que [apesar dos nomes citados nas declarações de `package` refletirem as alterações na capitalização das pastas, as pastas em si continuam iguais](https://github.com/projetoKhali/api4back/pull/9/commits/540b546f0efe8225c71f10054339f2cc679067c6#diff-c20f10235f1d266bfd758850749c6fc7487ccfd526f23373c16ece18366b88caR1)

![2024_04_06_15:03:07_sshot](https://github.com/projetoKhali/api4back/assets/93501477/2674db0b-4c81-4d02-ad5d-7a607bee6000)

Para contornar esse problema, fiz um [commit](https://github.com/projetoKhali/api4back/pull/9/commits/71615d4c739a84dfa1304ec06175b67b653aae98) que inclui um `_` no ***"conteúdo"*** do nome das pastas (alteração que vai "além" de apenas uma capitalização) e apenas então, reverti para o nome oficial porém com a capitalização corrigida.

![2024_04_06_15:05:18_sshot](https://github.com/projetoKhali/api4back/assets/93501477/f2d7ad01-4bfe-4032-bdac-071e457d128e)

Além disso, a pasta não pode conter nenhum caractere maiúsculo, ou seja, o nome `springApi4` continuaria inválido, por isso incluí a alteração para `springapi4`

2024-04-06 22:40 UTC, JhonatanLop requested changes
Em todas as entidades, para que o JPA funcione corretamente, é necessário adicionar a anotação `@NoArgsConstructo` que seria a anotação para criação de um construtor sem argumentos.

quando a conexão estiver pronta e o projeto for executado, o JPA vai reclamar pois ele precisa de um construtor sem argumentos.

link de referência
[fórum alura](https://cursos.alura.com.br/forum/topico-allargsconstructor-e-noargsconstructor-qual-o-real-uso-269551) - "@NoArgsConstructor" Qual o real uso? 
[stackoverflow](https://stackoverflow.com/questions/34241718/lombok-builder-and-jpa-default-constructor) - Lombok @Builder and JPA Default constructor

2024-04-06 22:40 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @ManyToOne
fui tentar executar o projeto e o java reclamou que a anotação `@ManyToOne` não foi importada.

2024-04-06 22:40 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Está faltando o import da anotação `GenerationType` do `jakarta.persistence`

2024-04-06 22:40 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    private Set<Qualifier> qualifiers;
Faltou importar o `Set` do java.util

2024-04-06 22:40 UTC, JhonatanLop commented on src/main/java/com/fatec/springAPI4/entity/Expertise.java
> +    @JoinColumn(name = "tk_id")
Faltou importar a anotação `@JoinColumn` do jakarta.persistence

2024-04-06 22:40 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/PartnerTrack.java
> +@Getter @Setter @AllArgsConstructor
Em todas as entidades, para que o JPA funcione corretamente, é necessário adicionar a anotação `@NoArgsConstructo` que seria a anotação para criação de um construtor sem argumentos.

quando a conexão estiver pronta e o projeto for executar, o JPA vai reclamar pois ele precisa de um construtor sem argumentos.

link de referência
[fórum alura](https://cursos.alura.com.br/forum/topico-allargsconstructor-e-noargsconstructor-qual-o-real-uso-269551) - "@NoArgsConstructor" Qual o real uso? 
[stackoverflow](https://stackoverflow.com/questions/34241718/lombok-builder-and-jpa-default-constructor) - Lombok @Builder and JPA Default constructor

2024-04-06 22:49 UTC, JhonatanLop requested changes

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/Expertise.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/Partner.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/PartnerExpertise.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/PartnerQualifier.java
> +@AllArgsConstructor
```suggestion
@AllArgsConstructor
@NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/Qualifier.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/Track.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-06 22:49 UTC, JhonatanLop commented on src/main/java/com/fatec/springapi4/entity/user/User.java
> +@Getter @Setter @AllArgsConstructor
```suggestion
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
```

2024-04-07 03:05 UTC, JhonatanLop approved these changes

2024-04-08 18:12 UTC, paulo-granthon approved these changes

2024-04-08 18:50 UTC, merged